language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-25
    - extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
    - ./gradlew build
before_install:
    - chmod +x gradlew
branches:
  only:
    - master
    - cabbage-impl